### ISSUE TITLE
pynvml.nvml.NVMLError_NotSupported: Not Supported

### ISSUE THREAD

**Issue by sweetboxwwy** [michal2409/xview2#3]
when I running main.py
traceback this:
C:\ProgramData\Anaconda3\python.exe D:/ChromeDownloads/xview2-master/xview2-master/main.py
Traceback (most recent call last):
  File "D:/ChromeDownloads/xview2-master/xview2-master/main.py", line 65, in <module>
    affinity = set_affinity(os.getenv("LOCAL_RANK", "0"), "socket_unique_interleaved")
  File "D:\ChromeDownloads\xview2-master\xview2-master\utils\gpu_affinity.py", line 139, in set_affinity
    set_socket_unique_affinity(gpu_id, world_size, "interleaved")
  File "D:\ChromeDownloads\xview2-master\xview2-master\utils\gpu_affinity.py", line 81, in set_socket_unique_affinity
    socket_affinities = [dev.getCpuAffinity() for dev in device_ids]
  File "D:\ChromeDownloads\xview2-master\xview2-master\utils\gpu_affinity.py", line 81, in <listcomp>
    socket_affinities = [dev.getCpuAffinity() for dev in device_ids]
  File "D:\ChromeDownloads\xview2-master\xview2-master\utils\gpu_affinity.py", line 34, in getCpuAffinity
    for j in pynvml.nvmlDeviceGetCpuAffinity(self.handle, device._nvml_affinity_elements):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvml\nvml.py", line 989, in nvmlDeviceGetCpuAffinity
    check_return(ret)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvml\nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported

Process finished with exit code 1
thanks very much!

**Comment by michal2409** [comment]
You can see if commenting line 65 in`main.py` file with: `affinity = set_affinity(os.getenv("LOCAL_RANK", "0"), "socket_unique_interleaved")` solves this problem.

**Comment by sweetboxwwy** [comment]
yes,it works,thanks a lot.but a new error:
Downloading: "https://s3.us-west-1.wasabisys.com/resnest/torch/resnest200-75117900.pth" to C:\Users\14548/.cache\torch\hub\checkpoints\resnest200-75117900.pth
Traceback (most recent call last):
  File "D:/ChromeDownloads/xview2-master/xview2-master/main.py", line 72, in <module>
    model = Model(args)
  File "D:\ChromeDownloads\xview2-master\xview2-master\model\plt.py", line 26, in __init__
    self.model = UNetLoc(args) if args.type == "pre" else get_dmg_unet(args)
  File "D:\ChromeDownloads\xview2-master\xview2-master\model\unet.py", line 41, in get_dmg_unet
    model = dmg_unets[args.dmg_model](args, nclass)
  File "D:\ChromeDownloads\xview2-master\xview2-master\model\unet.py", line 221, in __init__
    self.unet = UNetTemplate(args)
  File "D:\ChromeDownloads\xview2-master\xview2-master\model\unet.py", line 121, in __init__
    self.enc_chn, self.enc_l1, self.enc_l2, self.enc_l3, self.enc_l4, self.enc_l5 = get_encoder(
  File "D:\ChromeDownloads\xview2-master\xview2-master\model\unet.py", line 52, in get_encoder
    encoder = resnest[encoder_str](pretrained=pretrained, dilation=dilation)
  File "C:\ProgramData\Anaconda3\lib\site-packages\resnest\torch\resnest.py", line 59, in resnest200
    model.load_state_dict(torch.hub.load_state_dict_from_url(
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\hub.py", line 555, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\hub.py", line 425, in download_url_to_file
    u = urlopen(req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Process finished with exit code 1

**Comment by michal2409** [comment]
Are you running your code inside docker container as described in [installation](https://github.com/michal2409/xview2#installation) section?

I've checked and I don't have problems with checkpoint downloading. Please make sure you are running your code inside docker container such that all dependencies are properly installed.

**Comment by sweetboxwwy** [comment]
thank you so much, I will try it on
